apiVersion: skaffold/v2beta10
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: vetrip/employees-ui
      context: employees-ui
      docker:
        dockerfile: Dockerfile
    - image: vetrip/employees-api
      context: employees-api
      docker:
        dockerfile: Dockerfile.dev
deploy:
  kubectl:
    manifests:
      - k8s/ui-deployment.yaml
      - k8s/api-deployment.yaml
      - k8s/mysql-deployment.yaml
      - k8s/ui-cluster-ip-service.yaml
      - k8s/api-cluster-ip-service.yaml
      - k8s/mysql-cluster-ip-service.yaml
      - k8s/mysql-persistent-volume-claim.yaml
        
    

       