apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: aws-alb-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    #nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /*
            backend:
              serviceName: ui-cluster-ip-service
              servicePort: 80
          - pathType: Prefix
            path: /api/*
            backend:
              serviceName: api-cluster-ip-service
              servicePort: 8080

