apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: ui-cluster-ip-service
                port: 
                  number: 3100
          - pathType: Prefix
            path: /api/
            backend:
              service:
                name: api-cluster-ip-service
                port: 
                  number: 8080

